[package]
name = "modbit-tools"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
modbit-policy = { path = "../policy" }

[dev-dependencies]
uuid = { workspace = true }

[lints]
workspace = true
