[package]
name = "modbit-skills"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
sha2 = { workspace = true }
serde_json = { workspace = true }
modbit-tools = { path = "../tools" }
modbit-policy = { path = "../policy" }

[dev-dependencies]
uuid = { workspace = true }

[lints]
workspace = true
