[package]
name = "modbit-core-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
modbit-domain = { path = "../domain" }
modbit-event-store = { path = "../event-store" }
modbit-protocol = { path = "../protocol" }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
prost = "0.13"
prost-types = "0.13"
rusqlite = { workspace = true }

[[bin]]
name = "modbit-core"
path = "src/bin/modbit-core.rs"

[dev-dependencies]
uuid = { workspace = true }

[lints]
workspace = true
